### ISSUE TITLE
lifespan

### ISSUE THREAD

**Issue by kefkataran** [shinotype/shino-qa-tool#433]
QA tool suggests replacing "lifespan" with "life span" per Merriam-Webster - however it seems like MW recently swapped the too and now prefers "lifespan" as a compound word. I'm not sure if MW tracks when these changes are made somewhere, so I'm not sure when it happened but it seems recent and I just happened to stumble on it while editing a book. Screenshot attached.

![lifespan](https://github.com/shinotype/shino-qa-tool/assets/165875128/a6e244ec-5290-4bc9-b179-be1778d721cc)

**Comment by shinotype** [comment]
Hey, thanks for the issue report! I think you're actually the first person who has ever submitted an issue through here, haha. I'm planning to update the QA tool soon with a couple of QOL changes, and I'll roll the update for lifespan (and absent-minded and a couple of other terms) out at the same time. Should be within the next couple of weeks, when I find the time!

**Comment by kefkataran** [comment]
I just got pointed to the Github for this tool a bit ago, so I'm happy I could contribute! Thank you so much for all your hard work - this tool is absolutely invaluable for QAs!

**Comment by shinotype** [comment]
Fixed!
